import { useEffect, useRef, useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { RefreshCw } from "lucide-react";
import { toast } from "sonner";
import DashboardLayout from "@/components/layout/DashboardLayout";
import { SubscriptionGate } from "@/components/SubscriptionGate";
import { supabase } from "@/integrations/supabase/client";

const DEFAULT_TICKERS = ['NVDA', 'SPY', 'TSLA', 'AMZN', 'META', 'AMD', 'AAPL'];

const ACTION_LABELS: Record<string, string> = {
  strong_buy: "Strong Buy", buy: "Buy", hold: "Hold",
  watch: "Watch", exit: "Exit", strong_exit: "Strong Exit",
};

const FILTER_OPTIONS = [
  { value: 'all', label: 'All' },
  { value: 'strong_buy', label: 'Strong Buy' },
  { value: 'buy', label: 'Buy' },
  { value: 'watch', label: 'Watch' },
  { value: 'exit', label: 'Exit' },
];

// Only equities are currently generated by the signal engine.
// Multi-asset support (crypto, forex, etc.) will be added when the edge
// function supports non-equity tickers.
const ASSET_CLASS_OPTIONS = [
  { value: 'all',    label: 'All Assets' },
  { value: 'equity', label: 'Equities' },
];

const actionColor: Record<string, string> = {
  strong_buy: "text-bullish border-bullish/30 bg-bullish/5 glow-green",
  buy: "text-neutral border-neutral/30 bg-neutral/5 glow-blue",
  hold: "text-muted-foreground border-border bg-accent",
  watch: "text-watch border-watch/30 bg-watch/5 glow-yellow",
  exit: "text-bearish border-bearish/30 bg-bearish/5 glow-red",
  strong_exit: "text-bearish border-bearish/30 bg-bearish/5 glow-red",
};

export default function Signals() {
  const queryClient = useQueryClient();
  const [filter, setFilter] = useState('all');
  const [assetFilter, setAssetFilter] = useState('all');
  const hasAutoGenerated = useRef(false);

  const { data: signals = [], isLoading } = useQuery({
    queryKey: ['signals'],
    queryFn: async () => {
      const { data } = await supabase
        .from('signals')
        .select('*')
        .order('signal_score', { ascending: false });
      return data ?? [];
    },
  });

  const { mutate: generateSignals, isPending: isGenerating } = useMutation({
    mutationFn: async () => {
      const { data, error } = await supabase.functions.invoke('generate-signals', {
        body: { tickers: DEFAULT_TICKERS },
      });
      if (error) throw error;

      const generated: any[] = (data?.signals ?? []).filter((s: any) => !s.error);
      if (!generated.length) throw new Error('No signals returned from function');

      await supabase.from('signals').delete().not('id', 'is', null);

      const toInsert = generated.map((s: any) => ({
        ticker: s.ticker,
        asset_class: s.asset_class ?? 'equity',
        strategy_type: 'ai_generated',
        signal_score: s.signal_score,
        action: s.action,
        entry_price: s.entry_price ?? null,
        target_price: s.target_price ?? null,
        stop_price: s.stop_price ?? null,
        technical_score: s.technical_score,
        sentiment_score: s.sentiment_score,
        options_flow_score: s.options_flow_score ?? null,
        macro_score: s.macro_score,
        reasoning: s.reasoning ?? [],
        expires_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      }));

      const { error: insertErr } = await supabase.from('signals').insert(toInsert);
      if (insertErr) throw insertErr;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['signals'] });
      toast.success('Signals refreshed');
    },
    onError: (err: any) => {
      toast.error(`Signal generation failed: ${err.message ?? 'Unknown error'}`);
    },
  });

  // Auto-generate on first load if table is empty
  useEffect(() => {
    if (!isLoading && signals.length === 0 && !hasAutoGenerated.current && !isGenerating) {
      hasAutoGenerated.current = true;
      generateSignals();
    }
  }, [isLoading, signals.length]);

  const filtered = signals
    .filter((s) => filter === 'all' || s.action === filter)
    .filter((s) => assetFilter === 'all' || (s.asset_class ?? 'equity') === assetFilter);

  const sorted = [...filtered].sort((a, b) => (b.signal_score ?? 0) - (a.signal_score ?? 0));

  return (
    <DashboardLayout>
      <SubscriptionGate>
      <div className="space-y-6">
      <div className="flex flex-col gap-3">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <h2 className="font-display text-xl font-bold text-foreground">AI Signals</h2>
          <button
            onClick={() => generateSignals()}
            disabled={isGenerating}
            className="flex items-center gap-1.5 rounded-lg border border-border bg-card px-3 py-1.5 font-body text-xs font-medium text-muted-foreground transition-fast hover:border-bullish/30 hover:text-foreground disabled:cursor-not-allowed disabled:opacity-50"
          >
            <RefreshCw className={`h-3 w-3 ${isGenerating ? 'animate-spin' : ''}`} />
            {isGenerating ? 'Generating…' : 'Refresh Signals'}
          </button>
        </div>
        {/* Asset class filter */}
        <div className="flex flex-wrap gap-1.5">
          {ASSET_CLASS_OPTIONS.map((f) => (
            <button
              key={f.value}
              onClick={() => setAssetFilter(f.value)}
              className={`rounded-lg border px-3 py-1.5 font-mono text-xs font-bold transition-fast ${
                assetFilter === f.value
                  ? "border-primary/40 bg-primary/10 text-primary"
                  : "border-border bg-card text-muted-foreground hover:text-foreground"
              }`}
            >
              {f.label}
            </button>
          ))}
        </div>
        {/* Action filter */}
        <div className="flex flex-wrap gap-1.5">
          {FILTER_OPTIONS.map((f) => (
            <button
              key={f.value}
              onClick={() => setFilter(f.value)}
              className={`rounded-lg px-3 py-1.5 font-body text-xs font-medium transition-fast ${
                filter === f.value ? "bg-accent text-foreground" : "text-muted-foreground hover:bg-accent/50"
              }`}
            >
              {f.label}
            </button>
          ))}
        </div>
      </div>

      {(isLoading || isGenerating) && (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          {Array.from({ length: 6 }).map((_, i) => (
            <div key={i} className="h-48 animate-pulse rounded-lg border border-border bg-card" />
          ))}
        </div>
      )}

      {!isLoading && !isGenerating && sorted.length === 0 && (
        <div className="flex flex-col items-center justify-center rounded-lg border border-border bg-card py-16 text-center">
          <p className="text-sm font-medium text-foreground">No signals found</p>
          <p className="mt-1 text-xs text-muted-foreground">
            Click Refresh to generate signals, or check that POLYGON_KEY and OPENAI_API_KEY are set in Supabase Edge Function secrets.
          </p>
        </div>
      )}

      {!isLoading && !isGenerating && sorted.length > 0 && (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          {sorted.map((s) => {
            const action = s.action ?? 'hold';
            const reasons = (s.reasoning as string[] | null) ?? [];
            return (
              <div
                key={s.id}
                className={`rounded-lg border p-5 transition-fast hover:scale-[1.01] ${actionColor[action] ?? ''}`}
              >
                <div className="flex items-center justify-between">
                  <div>
                    <span className="font-mono text-xl font-bold">{s.ticker}</span>
                    <span className="ml-2 text-xs text-muted-foreground">{s.strategy_type ?? '—'}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="rounded-md border px-2 py-0.5 font-mono text-xs font-semibold uppercase">
                      {ACTION_LABELS[action] ?? action}
                    </span>
                    <span className="font-mono text-2xl font-bold">{s.signal_score ?? '—'}</span>
                  </div>
                </div>
                <div className="mt-3 grid grid-cols-3 gap-2">
                  {[
                    { l: "Entry", v: s.entry_price ? `$${s.entry_price}` : "—" },
                    { l: "Target", v: s.target_price ? `$${s.target_price}` : "—" },
                    { l: "Stop", v: s.stop_price ? `$${s.stop_price}` : "—" },
                  ].map((i) => (
                    <div key={i.l} className="rounded bg-background p-2 text-center">
                      <span className="block text-[10px] uppercase text-muted-foreground">{i.l}</span>
                      <span className="font-mono text-sm font-semibold text-foreground">{i.v}</span>
                    </div>
                  ))}
                </div>
                {s.position_size_dollars != null && (
                  <div className="mt-3">
                    <span className="text-[10px] uppercase text-muted-foreground">Size: </span>
                    <span className="font-mono text-xs">
                      ${s.position_size_dollars.toLocaleString()} ({s.position_size_pct ?? 0}%)
                    </span>
                  </div>
                )}
                <div className="mt-2 flex gap-3 text-[10px] text-muted-foreground">
                  {s.technical_score != null && <span>Tech {s.technical_score}</span>}
                  {s.sentiment_score != null && <span>Sent {s.sentiment_score}</span>}
                  {s.options_flow_score != null && <span>Flow {s.options_flow_score}</span>}
                  {s.macro_score != null && <span>Macro {s.macro_score}</span>}
                </div>
                {reasons.length > 0 && (
                  <ul className="mt-3 space-y-1">
                    {reasons.map((r, i) => (
                      <li key={i} className="flex gap-2 text-xs text-muted-foreground">
                        <span className="mt-0.5 h-1.5 w-1.5 shrink-0 rounded-full bg-current opacity-50" />
                        {r}
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            );
          })}
        </div>
      )}
      </div>
      </SubscriptionGate>
    </DashboardLayout>
  );
}
